#!/bin/bash
# Builds build/Ginga.app and build/ginga.
#
#   scripts/build-app.sh                       # release build
#   CONFIGURATION=debug scripts/build-app.sh
#   GINGA_SIGN_IDENTITY="Developer ID Application: …" scripts/build-app.sh
#   GINGA_ARCHS="arm64 x86_64" GINGA_VERSION=0.2.0 scripts/build-app.sh   # universal release (CI)
#
# GINGA_ARCHS: architectures to build, one `swift build --triple` each, joined with lipo (default:
# this Mac's). Works with the Command Line Tools alone. GINGA_VERSION: CFBundleShortVersionString,
# with CFBundleVersion derived from it (MAJOR*10000 + MINOR*100 + PATCH); default: Info.plist's.
#
# Signing: uses $GINGA_SIGN_IDENTITY, else a "Ginga Development" identity if present
# (scripts/create-dev-signing-identity.sh), else ad-hoc. With ad-hoc signing macOS forgets the
# Screen Recording permission after every rebuild because the code hash changes.
set -euo pipefail
cd "$(dirname "$0")/.."

configuration="${CONFIGURATION:-release}"
identity="${GINGA_SIGN_IDENTITY:-}"
if [[ -z "$identity" ]] && security find-identity -p codesigning 2>/dev/null | grep -q '"Ginga Development"'; then
    identity="Ginga Development"
fi

read -r -a archs <<< "${GINGA_ARCHS:-$(uname -m)}"
minimum="$(/usr/libexec/PlistBuddy -c 'Print :LSMinimumSystemVersion' Resources/Info.plist)"
bins=()
for arch in "${archs[@]}"; do
    triple=(--triple "$arch-apple-macosx$minimum")
    swift build -c "$configuration" "${triple[@]}" --product GingaApp
    swift build -c "$configuration" "${triple[@]}" --product ginga
    bins+=("$(swift build -c "$configuration" "${triple[@]}" --show-bin-path)")
done

# One binary per product: the single build's, or a fat one from all of them.
merge() {
    local product="$1" output="$2" inputs=()
    for bin in "${bins[@]}"; do inputs+=("$bin/$product"); done
    if (( ${#inputs[@]} == 1 )); then cp "${inputs[0]}" "$output"; else lipo -create "${inputs[@]}" -output "$output"; fi
}

app="build/Ginga.app"
rm -rf "$app"
mkdir -p "$app/Contents/MacOS" "$app/Contents/Resources"
merge GingaApp "$app/Contents/MacOS/GingaApp"
cp Resources/Info.plist "$app/Contents/Info.plist"
if [[ -n "${GINGA_VERSION:-}" ]]; then
    IFS=. read -r major minor patch <<< "${GINGA_VERSION%%-*}"
    /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $GINGA_VERSION" \
        -c "Set :CFBundleVersion $(( major * 10000 + minor * 100 + ${patch:-0} ))" "$app/Contents/Info.plist"
fi
cp Resources/AppIcon.icns "$app/Contents/Resources/AppIcon.icns"   # generated by brand/tools/export.py
cp -R Resources/*.lproj "$app/Contents/Resources/"                # localized Info.plist texts (pt-BR)
cp -R Resources/Fonts "$app/Contents/Resources/"                  # brand fonts (SIL OFL, licenses alongside)
merge ginga build/ginga

signing=(--force --options runtime --timestamp=none --entitlements Resources/Ginga.entitlements)

# Runs codesign but never waits on a keychain dialog forever (unattended builds): after
# $GINGA_SIGN_TIMEOUT seconds (default 30) it gives up so we can fall back to ad-hoc.
sign_with_timeout() {
    codesign "$@" &
    local pid=$!
    ( sleep "${GINGA_SIGN_TIMEOUT:-30}"; kill -TERM "$pid" 2>/dev/null ) &
    local watchdog=$!
    wait "$pid"
    local status=$?
    kill "$watchdog" 2>/dev/null
    wait "$watchdog" 2>/dev/null
    return $status
}

# ginga is a command-line tool: TCC attributes it to the terminal, so it needs no stable identity.
codesign --force --sign - build/ginga

if [[ -n "$identity" && "$identity" != "-" ]] && sign_with_timeout "${signing[@]}" --sign "$identity" "$app"; then
    echo "signed with: $identity"
else
    [[ -n "$identity" && "$identity" != "-" ]] && echo "warning: signing with '$identity' failed or timed out (keychain prompt?) — falling back to ad-hoc; Screen Recording must be re-granted for this build" >&2
    codesign "${signing[@]}" --sign - "$app"
    echo "signed ad-hoc — Screen Recording permission must be re-granted after each rebuild (see docs/development.md)"
fi
codesign --verify --strict "$app"
echo "built $(pwd)/$app ($(lipo -archs "$app/Contents/MacOS/GingaApp"))"
